### ISSUE TITLE
paper?

### ISSUE THREAD

**Issue by jimiao1125** [abhishekkhare1998/EcgClassificationProject#2]
hello,does this repo is some paper's implement?

**Comment by abhishekkhare1998** [comment]
No, this is not the exact implementation, but it is inspired by the DWT feature extraction implementations in these papers - 
https://www.ajer.org/papers/v2(3)/G0234450.pdf
https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.1049.5330&rep=rep1&type=pdf
